import * as THREE from './assets/three.module.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],colors=['#ff6688','#ffc857','#55d6be','#6d8cff','#b978ff','#ff914d'],praises=['Fantástico!','Muito bem!','Boa!','És incrível!','Conseguiste!'];
const defaultState={puzzle:{level:0,pieces:[],completed:[]},paint:{row:null,col:0,image:'',color:'#ff6688'},blocks:{x:1,y:8,collected:[],placed:[],selected:'brick'}};
let state;try{state=Object.assign({},defaultState,JSON.parse(localStorage.dinoFunStateV11||'{}'));state.puzzle=Object.assign({},defaultState.puzzle,state.puzzle);state.paint=Object.assign({},defaultState.paint,state.paint);state.blocks=Object.assign({},defaultState.blocks,state.blocks)}catch(e){state=structuredClone(defaultState)}
let sound=true,audioCtx,puzzleLevel=state.puzzle.level,puzzlePieces=[],puzzleSelected=null,puzzleLocked=false,paintColor=state.paint.color,paintCategory=null,paintDrawing=0,paintImage=null,swRegistration,updateFound=false,manualUpdate=false,reloading=false;
const screens=$$('.screen');
function save(){localStorage.dinoFunStateV11=JSON.stringify(state);updateMenu()}
function show(id){screens.forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');$('#backBtn').classList.toggle('hidden',id==='menuScreen')}
function tone(f,d=.12,type='sine'){if(!sound)return;audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;o.type=type;g.gain.setValueAtTime(.06,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}
function celebrate(big=false){$('#praise').textContent=praises[Math.floor(Math.random()*praises.length)];const box=$('#celebration');box.className='celebration show'+(big?' big':'');tone(660,.1);setTimeout(()=>tone(880,.18),100);setTimeout(()=>box.className='celebration',900)}
function shuffle(a){return a.sort(()=>Math.random()-.5)}
function updateMenu(){const done=state.puzzle.completed.length;$('#puzzleMenuProgress').textContent=done?`${done} de 18 completos · continuar no ${state.puzzle.level+1}`:'18 imagens para montar';$('#paintMenuProgress').textContent=state.paint.row===null?'15 desenhos em 5 categorias':`Continuar: ${paintCategories[state.paint.row].drawings[state.paint.col]}`;$('#blockMenuProgress').textContent=state.blocks.collected.length||state.blocks.placed.length?`${state.blocks.collected.length} estrelas · ${state.blocks.placed.length} blocos`:'Explora, recolhe e constrói'}
function openGame(game){tone(520);if(game==='puzzle'){puzzleLevel=state.puzzle.level;buildPuzzle(true);show('puzzleScreen')}if(game==='paint'){if(state.paint.row!==null)startPainting(state.paint.row,state.paint.col,true);else showPaintChoice();show('paintScreen')}if(game==='blocks'){show('blocksScreen');initWorld3D();syncWorld3D()}}

const puzzleData=[
 ...['Bronto no prado','Tricerátops das flores','Estego do lago','T-Rex da selva','Pterodáctilo dos vulcões','Anquilo do jardim'].map((name,index)=>({name,image:'assets/dino-puzzles.jpg',cols:3,rows:2,index})),
 ...['Velociraptor do rio','Parassauro das flores','Paquicefalossauro das rochas','Diplodoco do arco-íris','Espinossauro da lagoa','Bebé T-Rex no ovo','Iguanodonte da floresta','Dino das borboletas','Estiracossauro do outono','Mosassauro no oceano','Estegossauro da praia','Braquiossauro da neve'].map((name,index)=>({name,image:'assets/dino-puzzles-2.jpg',cols:4,rows:3,index}))
];
function puzzleGrid(){return puzzleLevel<2?2:3}
function pieceStyle(piece,n){const p=puzzleData[puzzleLevel],pc=p.index%p.cols,pr=Math.floor(p.index/p.cols),col=piece%n,row=Math.floor(piece/n),x=(pc+col/n)/(p.cols-1/n)*100,y=(pr+row/n)/(p.rows-1/n)*100;return `background-image:url('${p.image}');background-size:${p.cols*n*100}% ${p.rows*n*100}%;background-position:${x}% ${y}%`}
function freshPuzzle(){const count=puzzleGrid()**2,pieces=shuffle([...Array(count).keys()]);if(pieces.every((v,i)=>v===i))pieces.push(pieces.shift());return pieces}
function buildPuzzle(resume=false){$('.puzzle-next')?.remove();puzzleSelected=null;puzzleLocked=false;const p=puzzleData[puzzleLevel],same=state.puzzle.level===puzzleLevel&&state.puzzle.pieces.length===puzzleGrid()**2;puzzlePieces=resume&&same?[...state.puzzle.pieces]:freshPuzzle();state.puzzle.level=puzzleLevel;state.puzzle.pieces=[...puzzlePieces];save();$('#puzzleLevel').textContent=`${puzzleLevel+1} de ${puzzleData.length}`;$('#puzzleStars').textContent=`⭐ ${state.puzzle.completed.length} / ${puzzleData.length}`;$('#puzzleProgress').style.width=`${state.puzzle.completed.length/puzzleData.length*100}%`;$('#puzzleTitle').textContent=p.name;$('#puzzleTip').textContent=`Puzzle ${puzzleGrid()} × ${puzzleGrid()} · toca em duas peças para trocar`;const ref=$('#puzzleReference'),pc=p.index%p.cols,pr=Math.floor(p.index/p.cols);ref.style.backgroundImage=`url('${p.image}')`;ref.style.backgroundSize=`${p.cols*100}% ${p.rows*100}%`;ref.style.backgroundPosition=`${pc/(p.cols-1)*100}% ${pr/(p.rows-1)*100}%`;renderPuzzle();renderPuzzleLevels()}
function renderPuzzle(){const n=puzzleGrid(),board=$('#puzzleBoard');board.style.setProperty('--grid',n);board.innerHTML='';puzzlePieces.forEach((piece,pos)=>{const b=document.createElement('button');b.className='puzzle-piece'+(pos===puzzleSelected?' selected':'')+(piece===pos?' placed':'');b.style.cssText=pieceStyle(piece,n);b.setAttribute('aria-label',`Peça ${pos+1}`);b.onclick=()=>selectPuzzle(pos);board.appendChild(b)})}
function selectPuzzle(pos){if(puzzleLocked)return;if(puzzleSelected===null){puzzleSelected=pos;tone(350,.06);renderPuzzle();return}if(puzzleSelected===pos){puzzleSelected=null;renderPuzzle();return}[puzzlePieces[puzzleSelected],puzzlePieces[pos]]=[puzzlePieces[pos],puzzlePieces[puzzleSelected]];puzzleSelected=null;state.puzzle.pieces=[...puzzlePieces];save();renderPuzzle();if(puzzlePieces.every((v,i)=>v===i))finishPuzzle()}
function finishPuzzle(){puzzleLocked=true;if(!state.puzzle.completed.includes(puzzleLevel))state.puzzle.completed.push(puzzleLevel);save();renderPuzzleLevels();$('#puzzleStars').textContent=`⭐ ${state.puzzle.completed.length} / ${puzzleData.length}`;$('#puzzleProgress').style.width=`${state.puzzle.completed.length/puzzleData.length*100}%`;$('#puzzleTip').textContent='Imagem completa! Podes repetir quando quiseres ⭐';celebrate(true);setTimeout(()=>{const b=document.createElement('button');b.className='primary-btn puzzle-next';const next=Math.min(puzzleLevel+1,puzzleData.length-1);b.textContent=puzzleLevel<puzzleData.length-1?'Próximo puzzle →':'Repetir este puzzle ↻';b.onclick=()=>{puzzleLevel=next;buildPuzzle(false)};$('#puzzleBoard').after(b)},700)}
function renderPuzzleLevels(){const box=$('#puzzleLevels'),max=Math.min(puzzleData.length-1,Math.max(0,...state.puzzle.completed)+1);box.innerHTML='';puzzleData.forEach((p,i)=>{const b=document.createElement('button'),done=state.puzzle.completed.includes(i),open=i<=max||done;b.textContent=done?`✓ ${i+1}`:`${open?'🧩':'🔒'} ${i+1}`;b.disabled=!open;b.className=(done?'done ':'')+(i===puzzleLevel?'active':'');b.onclick=()=>{puzzleLevel=i;box.classList.add('hidden');buildPuzzle(i===state.puzzle.level)};box.appendChild(b)})}

const paintCategories=[{name:'Dinossauros',icon:'🦕',drawings:['Brontossauro','Tricerátops','Estegossauro']},{name:'Carros',icon:'🚗',drawings:['Carro feliz','Carro de corrida','Jipe']},{name:'Camiões',icon:'🚚',drawings:['Camião basculante','Carro de bombeiros','Betoneira']},{name:'Motas',icon:'🏍️',drawings:['Scooter','Moto de cross','Moto clássica']},{name:'Animais',icon:'🦁',drawings:['Leão','Elefante','Girafa']}];
function showPaintChoice(){savePaint();paintCategory=null;$('#paintChoice').classList.remove('hidden');$('#paintPlay').classList.add('hidden');$('#drawingPrompt').classList.add('hidden');$('#drawingChoices').innerHTML='';const box=$('#paintCategories');box.innerHTML='';paintCategories.forEach((cat,i)=>{const b=document.createElement('button');b.className='paint-category';b.innerHTML=`<span>${cat.icon}</span><strong>${cat.name}</strong><small>3 desenhos</small>`;b.onclick=()=>choosePaintCategory(i);box.appendChild(b)})}
function choosePaintCategory(index){paintCategory=index;$$('.paint-category').forEach((b,i)=>b.classList.toggle('active',i===index));$('#drawingPrompt').classList.remove('hidden');const box=$('#drawingChoices');box.innerHTML='';paintCategories[index].drawings.forEach((name,col)=>{const b=document.createElement('button');b.className='drawing-thumb';b.innerHTML=`<span></span><strong>${name}</strong>`;const preview=b.querySelector('span');preview.style.backgroundImage="url('assets/paint-atlas.png')";preview.style.backgroundSize='300% 500%';preview.style.backgroundPosition=`${col*50}% ${index*25}%`;b.onclick=()=>startPainting(index,col,false);box.appendChild(b)})}
function buildPalette(){const p=$('#palette');p.innerHTML='';colors.concat(['#9b5de5','#00bbf9','#8dd35f','#8b5e3c','#fff']).forEach(c=>{const b=document.createElement('button');b.style.background=c;b.classList.toggle('active',c===paintColor);b.onclick=()=>{paintColor=c;state.paint.color=c;save();$$('#palette button').forEach(x=>x.classList.remove('active'));b.classList.add('active')};p.appendChild(b)})}
function startPainting(row,col,resume=false){savePaint();paintCategory=row;paintDrawing=col;state.paint.row=row;state.paint.col=col;if(!resume)state.paint.image='';save();$('#paintChoice').classList.add('hidden');$('#paintPlay').classList.remove('hidden');$('#paintName').textContent=paintCategories[row].drawings[col];buildPalette();drawPaintImage(resume)}
function drawPaintImage(resume=false){if(!paintImage){paintImage=new Image();paintImage.src='assets/paint-atlas.png';paintImage.onload=()=>drawPaintImage(resume);return}if(!paintImage.complete)return;const c=$('#colorCanvas'),ctx=c.getContext('2d',{willReadFrequently:true}),drawBase=()=>{const sw=paintImage.naturalWidth/3,sh=paintImage.naturalHeight/5;ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(paintImage,paintDrawing*sw,paintCategory*sh,sw,sh,0,0,c.width,c.height)};if(resume&&state.paint.image){const saved=new Image();saved.onload=()=>ctx.drawImage(saved,0,0,c.width,c.height);saved.onerror=drawBase;saved.src=state.paint.image}else drawBase()}
function savePaint(){if(paintCategory===null)return;try{state.paint.image=$('#colorCanvas').toDataURL('image/webp',.75);state.paint.row=paintCategory;state.paint.col=paintDrawing;save()}catch(e){}}
function hexRgb(hex){const n=parseInt(hex.slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255]}
function floodPaint(x,y,color){const c=$('#colorCanvas'),ctx=c.getContext('2d',{willReadFrequently:true}),img=ctx.getImageData(0,0,c.width,c.height),d=img.data,w=c.width,h=c.height,start=(y*w+x)*4,target=[d[start],d[start+1],d[start+2]];if((target[0]+target[1]+target[2])/3<165)return;const fill=hexRgb(color),stack=[y*w+x],seen=new Uint8Array(w*h);while(stack.length){const p=stack.pop();if(seen[p])continue;seen[p]=1;const i=p*4,r=d[i],g=d[i+1],b=d[i+2];if(Math.abs(r-target[0])+Math.abs(g-target[1])+Math.abs(b-target[2])>75)continue;d[i]=fill[0];d[i+1]=fill[1];d[i+2]=fill[2];const px=p%w,py=(p/w)|0;if(px>0)stack.push(p-1);if(px<w-1)stack.push(p+1);if(py>0)stack.push(p-w);if(py<h-1)stack.push(p+w)}ctx.putImageData(img,0,0);savePaint();tone(520,.06)}
function canvasPaint(e){const c=$('#colorCanvas'),r=c.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)*c.width/r.width),y=Math.floor((e.clientY-r.top)*c.height/r.height);floodPaint(x,y,paintColor)}
function surprisePaint(){const palette=colors.concat(['#9b5de5','#00bbf9','#8dd35f']);for(let i=0;i<18;i++)floodPaint(30+Math.floor(Math.random()*340),30+Math.floor(Math.random()*340),palette[i%palette.length]);savePaint();celebrate()}

const worldStars=[[2,7],[4,8],[7,7],[8,5],[6,3],[3,3],[1,1],[8,1]];
let world3D,worldScene,worldCamera,worldRenderer,player3D,starMeshes=[],placedGroup,worldClock;
function mat(color,extra={}){return new THREE.MeshStandardMaterial({color,roughness:.72,metalness:.04,...extra})}
function mesh(geometry,material,x=0,y=0,z=0){const m=new THREE.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;return m}
function addTree(x,z,scale=1){const g=new THREE.Group();g.add(mesh(new THREE.CylinderGeometry(.22,.3,2,8),mat(0x825126),0,1,0));g.add(mesh(new THREE.ConeGeometry(1.15,2.6,9),mat(0x2b9b52),0,2.6,0));g.position.set(x,0,z);g.scale.setScalar(scale);worldScene.add(g)}
function makePlayer(){const g=new THREE.Group(),skin=mat(0xf2b38a),shirt=mat(0x5b68e8),jeans=mat(0x263a70),hair=mat(0x50301f);g.add(mesh(new THREE.BoxGeometry(.9,1.15,.55),shirt,0,1.65,0));g.add(mesh(new THREE.BoxGeometry(.72,.72,.7),skin,0,2.58,0));g.add(mesh(new THREE.BoxGeometry(.78,.22,.72),hair,0,2.91,0));g.add(mesh(new THREE.BoxGeometry(.3,.9,.35),jeans,-.24,.58,0));g.add(mesh(new THREE.BoxGeometry(.3,.9,.35),jeans,.24,.58,0));g.add(mesh(new THREE.BoxGeometry(.24,1,.3),skin,-.62,1.67,0));g.add(mesh(new THREE.BoxGeometry(.24,1,.3),skin,.62,1.67,0));return g}
function initWorld3D(){if(world3D)return;world3D=true;const canvas=$('#blockCanvas');worldRenderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});worldRenderer.setPixelRatio(Math.min(devicePixelRatio,2));worldRenderer.shadowMap.enabled=true;worldRenderer.shadowMap.type=THREE.PCFSoftShadowMap;worldRenderer.setClearColor(0x72c9ff);worldScene=new THREE.Scene();worldScene.fog=new THREE.Fog(0x86ceec,17,34);worldCamera=new THREE.PerspectiveCamera(52,1,.1,100);worldScene.add(new THREE.HemisphereLight(0xdff5ff,0x41612e,2.4));const sun=new THREE.DirectionalLight(0xfff3d0,3.2);sun.position.set(-8,14,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-16;sun.shadow.camera.right=16;sun.shadow.camera.top=16;sun.shadow.camera.bottom=-16;worldScene.add(sun);const ground=mesh(new THREE.PlaneGeometry(24,24,1,1),mat(0x65b64c),0,0,0);ground.rotation.x=-Math.PI/2;worldScene.add(ground);const path=mesh(new THREE.PlaneGeometry(4,22),mat(0xd9b477),0,.015,0);path.rotation.x=-Math.PI/2;worldScene.add(path);[-9,-7,-5,5,7,9].forEach((x,i)=>{addTree(x,-7+(i%3)*6,.8+(i%2)*.2);addTree(x,7-(i%3)*5,.75)});for(let i=0;i<7;i++){const mountain=mesh(new THREE.ConeGeometry(2.5+i%2,5+i%3,7),mat(i%2?0x7aa46e:0x718c86),-12+i*4,2.1,-13);worldScene.add(mountain)}const pond=mesh(new THREE.CylinderGeometry(3.2,3.2,.16,32),mat(0x42b9dd,{transparent:true,opacity:.82}),-7,.08,3);worldScene.add(pond);player3D=makePlayer();worldScene.add(player3D);placedGroup=new THREE.Group();worldScene.add(placedGroup);worldStars.forEach((p,i)=>{const s=mesh(new THREE.OctahedronGeometry(.45,0),mat(0xffd640,{emissive:0xff9d00,emissiveIntensity:.7}),p[0]-5,1.2,p[1]-5);s.userData.index=i;starMeshes.push(s);worldScene.add(s)});worldClock=new THREE.Clock();animateWorld()}
function makePlaced(b){const color={grass:0x4fbd57,brick:0xbd573e,water:0x37aee2,flower:0xff73b7}[b.t],h=b.t==='water'?.25:1;const cube=mesh(new THREE.BoxGeometry(1,h,1),mat(color,{transparent:b.t==='water',opacity:b.t==='water'?.75:1}),b.x-5,h/2,b.y-5);if(b.t==='flower'){const stem=mesh(new THREE.CylinderGeometry(.07,.09,.8,7),mat(0x319b4a),0,.75,0),bloom=mesh(new THREE.SphereGeometry(.3,10,8),mat(0xffe05b),0,1.2,0);cube.add(stem,bloom)}return cube}
function syncWorld3D(){if(!world3D)return;player3D.position.set(state.blocks.x-5,0,state.blocks.y-5);starMeshes.forEach(s=>s.visible=!state.blocks.collected.includes(s.userData.index));placedGroup.clear();state.blocks.placed.forEach(b=>placedGroup.add(makePlaced(b)));$('#blockScore').textContent=`⭐ ${state.blocks.collected.length}/${worldStars.length} · 🧱 ${state.blocks.placed.length}`;$$('[data-block]').forEach(b=>b.classList.toggle('active',b.dataset.block===state.blocks.selected));save()}
function animateWorld(){requestAnimationFrame(animateWorld);if(!worldRenderer)return;const canvas=worldRenderer.domElement,w=canvas.clientWidth||440,h=canvas.clientHeight||440;if(canvas.width!==Math.floor(w*Math.min(devicePixelRatio,2))||canvas.height!==Math.floor(h*Math.min(devicePixelRatio,2))){worldRenderer.setSize(w,h,false);worldCamera.aspect=w/h;worldCamera.updateProjectionMatrix()}const t=worldClock.getElapsedTime();starMeshes.forEach((s,i)=>{s.rotation.y=t*1.8+i;s.position.y=1.3+Math.sin(t*2+i)*.18});const target=new THREE.Vector3(player3D.position.x+7,7,player3D.position.z+9);worldCamera.position.lerp(target,.07);worldCamera.lookAt(player3D.position.x,1.2,player3D.position.z);worldRenderer.render(worldScene,worldCamera)}
function movePlayer(dx,dy){state.blocks.x=Math.max(0,Math.min(10,state.blocks.x+dx));state.blocks.y=Math.max(0,Math.min(10,state.blocks.y+dy));player3D.rotation.y=dx?dx>0?Math.PI/2:-Math.PI/2:dy>0?0:Math.PI;worldStars.forEach((p,i)=>{if(p[0]===state.blocks.x&&p[1]===state.blocks.y&&!state.blocks.collected.includes(i)){state.blocks.collected.push(i);celebrate();$('#blockTip').textContent=state.blocks.collected.length===8?'Encontraste todas as estrelas! Agora constrói livremente 🏆':'Encontraste uma estrela! ⭐'}});syncWorld3D()}
function placeBlock(){const ahead={x:state.blocks.x,y:Math.max(0,state.blocks.y-1),t:state.blocks.selected},i=state.blocks.placed.findIndex(v=>v.x===ahead.x&&v.y===ahead.y);if(i>=0)state.blocks.placed[i]=ahead;else state.blocks.placed.push(ahead);tone(430,.08);syncWorld3D()}
function resetWorld(){state.blocks=structuredClone(defaultState.blocks);save();syncWorld3D();$('#blockTip').textContent='Novo mundo 3D criado! Apanha estrelas e constrói.'}

function updateMessage(text,type=''){const box=$('#updateStatus');box.textContent=text;box.className=`update-status ${type}`;clearTimeout(updateMessage.timer);updateMessage.timer=setTimeout(()=>box.classList.add('hidden'),4200)}
async function checkUpdate(){if(!swRegistration){updateMessage('Atualizações indisponíveis','bad');return}manualUpdate=true;updateFound=false;updateMessage('🔎 A procurar uma nova versão…');try{await swRegistration.update();setTimeout(()=>{if(!updateFound)updateMessage('✅ Já tens a versão mais recente · v1.11','good')},1400)}catch(e){updateMessage('Liga a internet e tenta novamente','bad')}}
async function setupUpdates(){if(!('serviceWorker'in navigator)||location.hostname==='localhost'||location.hostname==='127.0.0.1')return;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(manualUpdate&&!reloading){reloading=true;location.reload()}});try{swRegistration=await navigator.serviceWorker.register('./sw.js');swRegistration.addEventListener('updatefound',()=>{updateFound=true;updateMessage('🦕 Nova versão encontrada. A atualizar…')})}catch(e){}}

$$('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));$('#togglePuzzleLevels').onclick=()=>$('#puzzleLevels').classList.toggle('hidden');$('#paintBack').onclick=showPaintChoice;$('#colorCanvas').onclick=canvasPaint;$('#clearPaint').onclick=()=>{state.paint.image='';drawPaintImage(false);save()};$('#randomPaint').onclick=surprisePaint;$$('[data-move]').forEach(b=>b.onclick=()=>{const m=b.dataset.move;movePlayer(m==='right'?1:m==='left'?-1:0,m==='down'?1:m==='up'?-1:0)});$$('[data-block]').forEach(b=>b.onclick=()=>{state.blocks.selected=b.dataset.block;syncWorld3D()});$('[data-action="place"]').onclick=placeBlock;$('#resetBlocks').onclick=resetWorld;$('#backBtn').onclick=()=>{savePaint();show('menuScreen');updateMenu()};$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊':'🔇'};$('#updateBtn').onclick=checkUpdate;$('#updateStatus').onclick=checkUpdate;updateMenu();show('menuScreen');window.addEventListener('load',setupUpdates);
