const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen'),colors=['#ff6688','#ffc857','#55d6be','#6d8cff','#b978ff','#ff914d'],sets=[{name:'CORES',icon:'🎨',items:colors,color:true},{name:'NÚMEROS',icon:'🔢',items:['1','2','3','4','5','6','7','8']},{name:'LETRAS',icon:'🔤',items:['A','B','C','D','E','F','G','H']},{name:'ANIMAIS',icon:'🐾',items:['🦁','🐼','🐸','🐵','🐯','🐨','🦊','🐰']},{name:'DINOS',icon:'🦖',items:['🦖','🦕','🐊','🥚','🌋','🦴','🦎','🐲']}],praises=['Fantástico!','Muito bem!','Boa!','És incrível!','Conseguiste!'];
let level=1,score=0,best=Number(localStorage.dinoBest||0),sound=true,selected=[],locked=false,matched=0,audioCtx,paintColor='#ff6688',mathRound=1,mathScore=0,mathOperation='plus',lessonIndex=0,lessonStars=0,lessons=[],currentSpeech='';
function show(id){screens.forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');$('#backBtn').classList.toggle('hidden',id==='menuScreen');$('#bestLabel').textContent=`Recorde: ${best}`}
function tone(f,d=.12,type='sine'){if(!sound)return;audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;o.type=type;g.gain.setValueAtTime(.06,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}
function celebrate(big=false){$('#praise').textContent=praises[Math.floor(Math.random()*praises.length)];const box=$('#celebration');box.classList.remove('show','big');void box.offsetWidth;box.classList.add('show');if(big)box.classList.add('big');tone(660,.1);setTimeout(()=>tone(880,.18),100);setTimeout(()=>box.classList.remove('show','big'),900)}
function shuffle(a){return a.sort(()=>Math.random()-.5)}function saveBest(){if(score>best){best=score;localStorage.dinoBest=best}}
function openGame(g){tone(520);if(g==='lesson'){startLesson();show('lessonScreen')}if(g==='pairs'){level=1;score=0;buildPairs();show('pairsScreen')}if(g==='math'){mathRound=1;mathScore=0;showMathChoice();show('mathScreen')}if(g==='paint'){buildPalette();show('paintScreen')}}
function makeLessons(){return shuffle([
  {skill:'LETRAS',icon:'🔤',q:'Qual é a letra A?',s:'Toca na letra A',visual:'A de Abelha 🐝',choices:['A','E','O'],correct:'A'},
  {skill:'SONS DAS PALAVRAS',icon:'👂',q:'Qual começa com A?',s:'Qual destas palavras começa com o som A?',visual:'Aaaaa…',choices:['🐝 Abelha','🐘 Elefante','🦁 Leão'],correct:'🐝 Abelha'},
  {skill:'CONTAR',icon:'🔢',q:'Quantas maçãs vês?',s:'Conta as maçãs e escolhe o número certo',visual:'🍎 🍎 🍎 🍎',choices:['3','4','5'],correct:'4'},
  {skill:'NÚMEROS',icon:'5️⃣',q:'Encontra o número cinco',s:'Toca no número cinco',visual:'Mostra o que sabes!',choices:['2','5','8'],correct:'5'},
  {skill:'CORES',icon:'🌈',q:'Qual é a cor do sol?',s:'Qual é a cor do sol?',visual:'☀️',choices:['Amarelo','Azul','Roxo'],correct:'Amarelo'},
  {skill:'FORMAS',icon:'🔷',q:'Qual é o círculo?',s:'Toca no círculo',visual:'Procura a forma redonda',choices:['●','■','▲'],correct:'●'},
  {skill:'COMPARAR',icon:'🐘',q:'Qual é o maior?',s:'Qual destes animais é maior?',visual:'🐘   🐭',choices:['🐘 Elefante','🐭 Rato'],correct:'🐘 Elefante'},
  {skill:'SEQUÊNCIAS',icon:'🧩',q:'O que vem a seguir?',s:'Um, dois, três. Qual é o número seguinte?',visual:'1 · 2 · 3 · ?',choices:['4','5','2'],correct:'4'}
])}
function speak(text){currentSpeech=text;if(!sound||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pt-PT';u.rate=.82;u.pitch=1.12;speechSynthesis.speak(u)}
function startLesson(){lessonIndex=0;lessonStars=0;lessons=makeLessons();renderLesson()}
function renderLesson(){const t=lessons[lessonIndex];$('#lessonCounter').textContent=`${lessonIndex+1} de ${lessons.length}`;$('#lessonStars').textContent='★'.repeat(lessonStars)+'☆'.repeat(lessons.length-lessonStars);$('#lessonProgress').style.width=`${lessonIndex/lessons.length*100}%`;$('#lessonIcon').textContent=t.icon;$('#lessonSkill').textContent=t.skill;$('#lessonQuestion').textContent=t.q;$('#lessonVisual').textContent=t.visual;$('#lessonTip').textContent='Pensa com calma. Tu consegues!';const box=$('#lessonChoices');box.innerHTML='';shuffle([...t.choices]).forEach(choice=>{const b=document.createElement('button');b.textContent=choice;b.onclick=()=>answerLesson(b,choice,t);box.appendChild(b)});setTimeout(()=>speak(t.s),300)}
function answerLesson(btn,choice,task){if(choice===task.correct){$$('#lessonChoices button').forEach(b=>b.disabled=true);btn.classList.add('correct');lessonStars++;$('#lessonTip').textContent='Muito bem! Ganhaste uma estrela ⭐';celebrate();setTimeout(()=>{lessonIndex++;if(lessonIndex<lessons.length)renderLesson();else finishLesson()},1000)}else{btn.classList.add('wrong');$('#lessonTip').textContent='Quase! Tenta outra vez 😊';tone(160,.16,'sawtooth');speak('Quase. Tenta outra vez');setTimeout(()=>btn.classList.remove('wrong'),500)}}
function finishLesson(){localStorage.dinoLessonStars=Math.max(Number(localStorage.dinoLessonStars||0),lessonStars);$('#lessonCounter').textContent='Completo!';$('#lessonStars').textContent='★'.repeat(lessonStars);$('#lessonProgress').style.width='100%';$('#lessonIcon').textContent='🏆';$('#lessonSkill').textContent='AVENTURA COMPLETA';$('#lessonQuestion').textContent='Aprendeste muito hoje!';$('#lessonVisual').textContent=`${lessonStars} estrelas conquistadas`;$('#lessonChoices').innerHTML='<button id="repeatLesson">Jogar novamente</button>';$('#repeatLesson').onclick=startLesson;$('#lessonTip').textContent='Volta amanhã para continuar a aprender.';celebrate(true);speak('Parabéns! Completaste a aventura de aprendizagem')}
function buildPairs(){selected=[];locked=false;matched=0;const set=sets[(level-1)%sets.length],pairs=Math.min(2+Math.floor((level-1)/2),4),memory=level>=3,chosen=shuffle([...set.items]).slice(0,pairs),items=shuffle([...chosen,...chosen]);$('#levelLabel').textContent=level;$('#scoreLabel').textContent=score;$('#modeLabel').textContent=set.name+(memory?' · MEMÓRIA':'');$('#promptIcon').textContent=set.icon;$('#promptText').textContent=`Encontra os ${pairs} pares`;$('#pairsHint').textContent=memory?'Memoriza! As cartas vão esconder-se…':'Todos os pares contam neste nível';$('#progressBar').style.width=`${Math.min(100,level*10)}%`;const board=$('#board');board.innerHTML='';board.className='board '+(items.length>=8?'compact':'');items.forEach(item=>{const b=document.createElement('button');b.className='cube revealed';b.dataset.key=item;b.dataset.value=item;if(set.color)b.style.setProperty('--face',item);else b.textContent=item;b.onclick=()=>pickPair(b);board.appendChild(b)});if(memory){locked=true;setTimeout(()=>{$$('.cube').forEach(b=>{b.classList.remove('revealed');b.textContent=''});locked=false;$('#pairsHint').textContent='Agora encontra os pares escondidos!'},1800)}}
function pickPair(btn){if(locked||btn.classList.contains('matched')||selected.includes(btn))return;btn.classList.add('revealed','selected');if(!btn.style.getPropertyValue('--face'))btn.textContent=btn.dataset.value;selected.push(btn);tone(300,.06);if(selected.length<2)return;locked=true;const[a,b]=selected;if(a.dataset.key===b.dataset.key){a.classList.remove('selected');b.classList.remove('selected');a.classList.add('matched');b.classList.add('matched');matched+=2;score+=100+level*10;$('#scoreLabel').textContent=score;celebrate();selected=[];locked=false;if(matched===$$('.cube').length){saveBest();setTimeout(()=>{$('#resultScore').textContent=score;$('#resultMessage').textContent=`Encontraste todos os pares do nível ${level}!`;show('resultScreen');celebrate(true)},950)}}else{a.classList.add('bad');b.classList.add('bad');score=Math.max(0,score-10);tone(140,.2,'sawtooth');setTimeout(()=>{a.classList.remove('bad','selected');b.classList.remove('bad','selected');if(level>=3){a.classList.remove('revealed');b.classList.remove('revealed');a.textContent='';b.textContent=''}selected=[];locked=false;$('#scoreLabel').textContent=score},600)}}
function showMathChoice(){$('#mathChoice').classList.remove('hidden');$('#mathPlay').classList.add('hidden')}
function startMath(op){mathOperation=op;mathRound=1;mathScore=0;$('#mathChoice').classList.add('hidden');$('#mathPlay').classList.remove('hidden');buildMath()}
function buildMath(){let a=1+Math.floor(Math.random()*Math.min(6,mathRound+2)),b=1+Math.floor(Math.random()*Math.min(5,mathRound+1));if(mathOperation==='minus'&&b>a)[a,b]=[b,a];const right=mathOperation==='plus'?a+b:a-b,sign=mathOperation==='plus'?'+':'−';$('#mathRound').textContent=mathRound;$('#mathScore').textContent=mathScore;$('#mathModeLabel').textContent=mathOperation==='plus'?'CONTA DE MAIS':'CONTA DE MENOS';$('#equation').innerHTML=`<div>${'🦕'.repeat(a)}</div><b>${sign}</b><div>${'🦖'.repeat(b)}</div><b>= ?</b>`;const wrong=shuffle([...new Set([Math.max(0,right-1),right+1,right+2].filter(n=>n!==right))]).slice(0,2),choices=shuffle([right,...wrong]);const box=$('#answers');box.innerHTML='';choices.forEach(n=>{const x=document.createElement('button');x.textContent=n;x.onclick=()=>{if(n===right){mathScore+=50;mathRound++;x.classList.add('correct');celebrate();setTimeout(buildMath,900)}else{tone(140,.2,'sawtooth');x.classList.add('wrong');setTimeout(()=>x.classList.remove('wrong'),400)}};box.appendChild(x)})}
function buildPalette(){const p=$('#palette');p.innerHTML='';colors.concat(['#9b5de5','#00bbf9','#fff']).forEach(c=>{const b=document.createElement('button');b.style.background=c;b.onclick=()=>{paintColor=c;$$('#palette button').forEach(x=>x.classList.remove('active'));b.classList.add('active');tone(420,.05)};p.appendChild(b)});p.firstChild.classList.add('active')}
function clearPaint(){$('#sky').style.fill='#d9f2ff';$('#ground').style.fill='#a8e6a3';['body','neck','tail','leg1','leg2'].forEach(id=>$('#'+id).style.fill='#f7f4e9');['spot1','spot2','spot3'].forEach(id=>$('#'+id).style.fill='#fff')}
$$('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));$$('.operation-card').forEach(b=>b.onclick=()=>startMath(b.dataset.op));$('#speakBtn').onclick=()=>speak(currentSpeech);$('#changeOperation').onclick=showMathChoice;$('#nextBtn').onclick=()=>{level++;buildPairs();show('pairsScreen')};$('#backBtn').onclick=()=>{if('speechSynthesis'in window)speechSynthesis.cancel();saveBest();show('menuScreen')};$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊':'🔇';if(!sound&&'speechSynthesis'in window)speechSynthesis.cancel()};$$('.paint-part').forEach(p=>p.onclick=()=>{p.style.fill=paintColor;celebrate()});$('#clearPaint').onclick=clearPaint;clearPaint();show('menuScreen');if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
