const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen'),colors=['#ff6688','#ffc857','#55d6be','#6d8cff','#b978ff','#ff914d'],sets=[{name:'CORES',icon:'🎨',items:colors,color:true},{name:'NÚMEROS',icon:'🔢',items:['1','2','3','4','5','6','7','8']},{name:'LETRAS',icon:'🔤',items:['A','B','C','D','E','F','G','H']},{name:'ANIMAIS',icon:'🐾',items:['🦁','🐼','🐸','🐵','🐯','🐨','🦊','🐰']},{name:'DINOS',icon:'🦖',items:['🦖','🦕','🐊','🥚','🌋','🦴','🦎','🐲']}],praises=['Fantástico!','Muito bem!','Boa!','És incrível!','Conseguiste!'];
let level=1,score=0,best=Number(localStorage.dinoBest||0),sound=true,selected=[],locked=false,matched=0,audioCtx,paintColor='#ff6688',paintCategory=null,paintDrawing=0,paintImage=null,mathRound=0,mathScore=0,mathOperation='plus',mathTasks=[],mathSpeech='',lessonIndex=0,lessonStars=0,lessons=[],currentSpeech='',puzzleLevel=0,puzzlePieces=[],puzzleSelected=null,puzzleLocked=false;
function show(id){screens.forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');$('#backBtn').classList.toggle('hidden',id==='menuScreen');$('#bestLabel').textContent=`Recorde: ${best}`}
function tone(f,d=.12,type='sine'){if(!sound)return;audioCtx??=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;o.type=type;g.gain.setValueAtTime(.06,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}
function celebrate(big=false){$('#praise').textContent=praises[Math.floor(Math.random()*praises.length)];const box=$('#celebration');box.classList.remove('show','big');void box.offsetWidth;box.classList.add('show');if(big)box.classList.add('big');tone(660,.1);setTimeout(()=>tone(880,.18),100);setTimeout(()=>box.classList.remove('show','big'),900)}
function shuffle(a){return a.sort(()=>Math.random()-.5)}function saveBest(){if(score>best){best=score;localStorage.dinoBest=best}}
function openGame(g){tone(520);if(g==='lesson'){startLesson();show('lessonScreen')}if(g==='puzzle'){puzzleLevel=0;buildPuzzle();show('puzzleScreen')}if(g==='pairs'){level=1;score=0;buildPairs();show('pairsScreen')}if(g==='math'){mathRound=0;mathScore=0;showMathChoice();show('mathScreen')}if(g==='paint'){showPaintChoice();show('paintScreen')}}
function makeLessons(){return shuffle([
  {skill:'LETRAS',icon:'🔤',q:'Qual é a letra A?',s:'Toca na letra A',visual:'A de Abelha 🐝',choices:['A','E','O'],correct:'A'},
  {skill:'SONS DAS PALAVRAS',icon:'👂',q:'Qual começa com A?',s:'Qual destas palavras começa com o som A?',visual:'Aaaaa…',choices:['🐝 Abelha','🐘 Elefante','🦁 Leão'],correct:'🐝 Abelha'},
  {skill:'CONTAR',icon:'🔢',q:'Quantas maçãs vês?',s:'Conta as maçãs e escolhe o número certo',visual:'🍎 🍎 🍎 🍎',choices:['3','4','5'],correct:'4'},
  {skill:'NÚMEROS',icon:'5️⃣',q:'Encontra o número cinco',s:'Toca no número cinco',visual:'Mostra o que sabes!',choices:['2','5','8'],correct:'5'},
  {skill:'CORES',icon:'🌈',q:'Qual é a cor do sol?',s:'Qual é a cor do sol?',visual:'☀️',choices:['Amarelo','Azul','Roxo'],correct:'Amarelo'},
  {skill:'FORMAS',icon:'🔷',q:'Qual é o círculo?',s:'Toca no círculo',visual:'Procura a forma redonda',choices:['●','■','▲'],correct:'●'},
  {skill:'COMPARAR',icon:'🐘',q:'Qual é o maior?',s:'Qual destes animais é maior?',visual:'🐘   🐭',choices:['🐘 Elefante','🐭 Rato'],correct:'🐘 Elefante'},
  {skill:'SEQUÊNCIAS',icon:'🧩',q:'O que vem a seguir?',s:'Um, dois, três. Qual é o número seguinte?',visual:'1 · 2 · 3 · ?',choices:['4','5','2'],correct:'4'}
])}
function speak(text){currentSpeech=text;if(!sound||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pt-PT';u.rate=.82;u.pitch=1.12;speechSynthesis.speak(u)}
function startLesson(){lessonIndex=0;lessonStars=0;lessons=makeLessons();renderLesson()}
function renderLesson(){const t=lessons[lessonIndex];$('#lessonCounter').textContent=`${lessonIndex+1} de ${lessons.length}`;$('#lessonStars').textContent='★'.repeat(lessonStars)+'☆'.repeat(lessons.length-lessonStars);$('#lessonProgress').style.width=`${lessonIndex/lessons.length*100}%`;$('#lessonIcon').textContent=t.icon;$('#lessonSkill').textContent=t.skill;$('#lessonQuestion').textContent=t.q;$('#lessonVisual').textContent=t.visual;$('#lessonTip').textContent='Pensa com calma. Tu consegues!';const box=$('#lessonChoices');box.innerHTML='';shuffle([...t.choices]).forEach(choice=>{const b=document.createElement('button');b.textContent=choice;b.onclick=()=>answerLesson(b,choice,t);box.appendChild(b)});setTimeout(()=>speak(t.s),300)}
function answerLesson(btn,choice,task){if(choice===task.correct){$$('#lessonChoices button').forEach(b=>b.disabled=true);btn.classList.add('correct');lessonStars++;$('#lessonTip').textContent='Muito bem! Ganhaste uma estrela ⭐';celebrate();setTimeout(()=>{lessonIndex++;if(lessonIndex<lessons.length)renderLesson();else finishLesson()},1000)}else{btn.classList.add('wrong');$('#lessonTip').textContent='Quase! Tenta outra vez 😊';tone(160,.16,'sawtooth');speak('Quase. Tenta outra vez');setTimeout(()=>btn.classList.remove('wrong'),500)}}
function finishLesson(){localStorage.dinoLessonStars=Math.max(Number(localStorage.dinoLessonStars||0),lessonStars);$('#lessonCounter').textContent='Completo!';$('#lessonStars').textContent='★'.repeat(lessonStars);$('#lessonProgress').style.width='100%';$('#lessonIcon').textContent='🏆';$('#lessonSkill').textContent='AVENTURA COMPLETA';$('#lessonQuestion').textContent='Aprendeste muito hoje!';$('#lessonVisual').textContent=`${lessonStars} estrelas conquistadas`;$('#lessonChoices').innerHTML='<button id="repeatLesson">Jogar novamente</button>';$('#repeatLesson').onclick=startLesson;$('#lessonTip').textContent='Volta amanhã para continuar a aprender.';celebrate(true);speak('Parabéns! Completaste a aventura de aprendizagem')}
const puzzleData=[
  ...['Bronto no prado','Tricerátops das flores','Estego do lago','T-Rex da selva','Pterodáctilo dos vulcões','Anquilo do jardim'].map((name,index)=>({name,image:'assets/dino-puzzles.jpg',cols:3,rows:2,index})),
  ...['Velociraptor do rio','Parassauro das flores','Paquicefalossauro das rochas','Diplodoco do arco-íris','Espinossauro da lagoa','Bebé T-Rex no ovo','Iguanodonte da floresta','Dino das borboletas','Estiracossauro do outono','Mosassauro no oceano','Estegossauro da praia','Braquiossauro da neve'].map((name,index)=>({name,image:'assets/dino-puzzles-2.jpg',cols:4,rows:3,index}))
];
function puzzleGrid(){return puzzleLevel<2?2:3}
function pieceStyle(piece,n){const p=puzzleData[puzzleLevel],panelCol=p.index%p.cols,panelRow=Math.floor(p.index/p.cols),col=piece%n,row=Math.floor(piece/n),x=(panelCol+col/n)/(p.cols-1/n)*100,y=(panelRow+row/n)/(p.rows-1/n)*100;return `background-image:url('${p.image}');background-size:${p.cols*n*100}% ${p.rows*n*100}%;background-position:${x}% ${y}%`}
function buildPuzzle(){$('.puzzle-next')?.remove();puzzleSelected=null;puzzleLocked=false;const n=puzzleGrid(),count=n*n,total=puzzleData.length,p=puzzleData[puzzleLevel];puzzlePieces=shuffle([...Array(count).keys()]);if(puzzlePieces.every((v,i)=>v===i))puzzlePieces.push(puzzlePieces.shift());$('#puzzleLevel').textContent=`${puzzleLevel+1} de ${total}`;$('#puzzleStars').textContent=`⭐ ${puzzleLevel} / ${total}`;$('#puzzleProgress').style.width=`${puzzleLevel/total*100}%`;$('#puzzleTitle').textContent=p.name;$('#puzzleTip').textContent=`Puzzle ${n} × ${n} · toca em duas peças para trocar`;const ref=$('#puzzleReference'),pc=p.index%p.cols,pr=Math.floor(p.index/p.cols);ref.style.backgroundImage=`url('${p.image}')`;ref.style.backgroundSize=`${p.cols*100}% ${p.rows*100}%`;ref.style.backgroundPosition=`${pc/(p.cols-1)*100}% ${pr/(p.rows-1)*100}%`;renderPuzzle()}
function renderPuzzle(){const n=puzzleGrid(),board=$('#puzzleBoard');board.style.setProperty('--grid',n);board.innerHTML='';puzzlePieces.forEach((piece,pos)=>{const b=document.createElement('button');b.className='puzzle-piece'+(pos===puzzleSelected?' selected':'')+(piece===pos?' placed':'');b.style.cssText=pieceStyle(piece,n);b.setAttribute('aria-label',`Peça ${pos+1}`);b.onclick=()=>selectPuzzle(pos);board.appendChild(b)})}
function selectPuzzle(pos){if(puzzleLocked)return;if(puzzleSelected===null){puzzleSelected=pos;tone(350,.06);renderPuzzle();return}if(puzzleSelected===pos){puzzleSelected=null;renderPuzzle();return}const before=puzzlePieces.filter((v,i)=>v===i).length;[puzzlePieces[puzzleSelected],puzzlePieces[pos]]=[puzzlePieces[pos],puzzlePieces[puzzleSelected]];puzzleSelected=null;const after=puzzlePieces.filter((v,i)=>v===i).length;if(after>before)tone(620,.1);renderPuzzle();if(puzzlePieces.every((v,i)=>v===i))finishPuzzle()}
function finishPuzzle(){puzzleLocked=true;const total=puzzleData.length,last=puzzleLevel===total-1;$('#puzzleProgress').style.width=`${(puzzleLevel+1)/total*100}%`;$('#puzzleStars').textContent=`⭐ ${puzzleLevel+1} / ${total}`;$('#puzzleTip').textContent='Imagem completa! Excelente trabalho ⭐';celebrate(true);speak('Muito bem! Completaste o puzzle');setTimeout(()=>{const b=document.createElement('button');b.className='primary-btn puzzle-next';b.textContent=last?'Terminar aventura 🏆':'Próximo puzzle →';b.onclick=()=>{if(!last){puzzleLevel++;buildPuzzle()}else{show('menuScreen');celebrate(true)}};$('#puzzleBoard').after(b)},850)}
function buildPairs(){selected=[];locked=false;matched=0;const set=sets[(level-1)%sets.length],pairs=Math.min(2+Math.floor((level-1)/2),4),memory=level>=3,chosen=shuffle([...set.items]).slice(0,pairs),items=shuffle([...chosen,...chosen]);$('#levelLabel').textContent=level;$('#scoreLabel').textContent=score;$('#modeLabel').textContent=set.name+(memory?' · MEMÓRIA':'');$('#promptIcon').textContent=set.icon;$('#promptText').textContent=`Encontra os ${pairs} pares`;$('#pairsHint').textContent=memory?'Memoriza! As cartas vão esconder-se…':'Todos os pares contam neste nível';$('#progressBar').style.width=`${Math.min(100,level*10)}%`;const board=$('#board');board.innerHTML='';board.className='board '+(items.length>=8?'compact':'');items.forEach(item=>{const b=document.createElement('button');b.className='cube revealed';b.dataset.key=item;b.dataset.value=item;if(set.color)b.style.setProperty('--face',item);else b.textContent=item;b.onclick=()=>pickPair(b);board.appendChild(b)});if(memory){locked=true;setTimeout(()=>{$$('.cube').forEach(b=>{b.classList.remove('revealed');b.textContent=''});locked=false;$('#pairsHint').textContent='Agora encontra os pares escondidos!'},1800)}}
function pickPair(btn){if(locked||btn.classList.contains('matched')||selected.includes(btn))return;btn.classList.add('revealed','selected');if(!btn.style.getPropertyValue('--face'))btn.textContent=btn.dataset.value;selected.push(btn);tone(300,.06);if(selected.length<2)return;locked=true;const[a,b]=selected;if(a.dataset.key===b.dataset.key){a.classList.remove('selected');b.classList.remove('selected');a.classList.add('matched');b.classList.add('matched');matched+=2;score+=100+level*10;$('#scoreLabel').textContent=score;celebrate();selected=[];locked=false;if(matched===$$('.cube').length){saveBest();setTimeout(()=>{$('#resultScore').textContent=score;$('#resultMessage').textContent=`Encontraste todos os pares do nível ${level}!`;show('resultScreen');celebrate(true)},950)}}else{a.classList.add('bad');b.classList.add('bad');score=Math.max(0,score-10);tone(140,.2,'sawtooth');setTimeout(()=>{a.classList.remove('bad','selected');b.classList.remove('bad','selected');if(level>=3){a.classList.remove('revealed');b.classList.remove('revealed');a.textContent='';b.textContent=''}selected=[];locked=false;$('#scoreLabel').textContent=score},600)}}
function showMathChoice(){$('#mathChoice').classList.remove('hidden');$('#mathPlay').classList.add('hidden');if('speechSynthesis'in window)speechSynthesis.cancel()}
function numberChoices(n){return shuffle([...new Set([n,Math.max(0,n-1),n+1,n+2])]).slice(0,3).map(String)}
function makeMathTasks(op){if(op==='plus')return[
  {icon:'🍎',q:'Quantas maçãs há?',s:'Conta todas as maçãs',visual:'🍎 🍎 🍎',correct:'3',choices:['2','3','4']},
  {icon:'🦕',q:'Junta os dois grupos',s:'Dois dinossauros mais um dinossauro. Quantos são?',visual:'🦕🦕  +  🦖',correct:'3',choices:['2','3','4']},
  {icon:'➕',q:'Quanto é 3 mais 2?',s:'Quanto é três mais dois?',visual:'3 + 2 = ?',correct:'5',choices:['4','5','6']},
  {icon:'🔎',q:'Qual é o número escondido?',s:'Dois mais que número é igual a seis?',visual:'2 + ? = 6',correct:'4',choices:['3','4','5']},
  {icon:'🎈',q:'A Maria tinha 3 balões e ganhou 2',s:'A Maria tinha três balões e ganhou mais dois. Com quantos ficou?',visual:'🎈🎈🎈 + 🎈🎈',correct:'5',choices:['4','5','6']},
  {icon:'⚖️',q:'Qual conta dá mais?',s:'Qual destas contas tem o maior resultado?',visual:'Compara as contas',correct:'3 + 3',choices:['3 + 3','2 + 1','1 + 4']},
  {icon:'🧩',q:'Completa a sequência',s:'Dois, quatro, seis. Que número vem a seguir?',visual:'2 · 4 · 6 · ?',correct:'8',choices:['7','8','9']},
  {icon:'🏁',q:'Desafio final: 4 mais 3',s:'Desafio final. Quanto é quatro mais três?',visual:'🦖🦖🦖🦖 + 🦕🦕🦕',correct:'7',choices:['6','7','8']}
];return[
  {icon:'🍪',q:'Tira uma bolacha',s:'Havia quatro bolachas. Tiramos uma. Quantas ficam?',visual:'🍪 🍪 🍪 🍪  −  🍪',correct:'3',choices:['2','3','4']},
  {icon:'🦕',q:'Dois dinos foram embora',s:'Havia cinco dinossauros. Dois foram embora. Quantos ficaram?',visual:'🦕🦕🦕🦕🦕  −  🦕🦕',correct:'3',choices:['2','3','4']},
  {icon:'➖',q:'Quanto é 6 menos 2?',s:'Quanto é seis menos dois?',visual:'6 − 2 = ?',correct:'4',choices:['3','4','5']},
  {icon:'🔎',q:'Qual é o número escondido?',s:'Sete menos que número é igual a quatro?',visual:'7 − ? = 4',correct:'3',choices:['2','3','4']},
  {icon:'🐟',q:'Havia 5 peixes e 2 nadaram para longe',s:'Havia cinco peixes. Dois nadaram para longe. Quantos ficaram?',visual:'🐟🐟🐟🐟🐟  −  🐟🐟',correct:'3',choices:['2','3','4']},
  {icon:'⚖️',q:'Qual conta dá menos?',s:'Qual destas contas tem o menor resultado?',visual:'Compara as contas',correct:'4 − 3',choices:['4 − 3','5 − 2','6 − 2']},
  {icon:'🧩',q:'Conta para trás',s:'Oito, seis, quatro. Que número vem a seguir?',visual:'8 · 6 · 4 · ?',correct:'2',choices:['1','2','3']},
  {icon:'🏁',q:'Desafio final: 8 menos 3',s:'Desafio final. Quanto é oito menos três?',visual:'8 − 3 = ?',correct:'5',choices:['4','5','6']}
]}
function startMath(op){mathOperation=op;mathRound=0;mathScore=0;mathTasks=makeMathTasks(op);$('#mathChoice').classList.add('hidden');$('#mathPlay').classList.remove('hidden');$('#mathSpeakBtn').classList.remove('hidden');buildMath()}
function buildMath(){if(mathRound>=mathTasks.length){finishMath();return}const t=mathTasks[mathRound];mathSpeech=t.s;$('#mathStep').textContent=`${mathRound+1} de ${mathTasks.length}`;$('#mathStars').textContent='★'.repeat(mathScore)+'☆'.repeat(mathTasks.length-mathScore);$('#mathProgress').style.width=`${mathRound/mathTasks.length*100}%`;$('#mathModeLabel').textContent=mathOperation==='plus'?'AVENTURA DE SOMAR':'AVENTURA DE SUBTRAIR';$('#mathIcon').textContent=t.icon;$('#mathQuestion').textContent=t.q;$('#equation').textContent=t.visual;$('#mathTip').textContent='Pensa com calma. Tu consegues!';const box=$('#answers');box.innerHTML='';shuffle([...t.choices]).forEach(n=>{const x=document.createElement('button');x.textContent=n;x.onclick=()=>{if(n===t.correct){$$('#answers button').forEach(b=>b.disabled=true);mathScore++;x.classList.add('correct');$('#mathTip').textContent='Certo! Ganhaste uma estrela ⭐';celebrate();setTimeout(()=>{mathRound++;buildMath()},1000)}else{tone(140,.2,'sawtooth');x.classList.add('wrong');$('#mathTip').textContent='Quase! Conta novamente 😊';speak('Quase. Conta novamente');setTimeout(()=>x.classList.remove('wrong'),450)}};box.appendChild(x)});setTimeout(()=>speak(t.s),250)}
function finishMath(){$('#mathStep').textContent='Completo!';$('#mathStars').textContent='★★★★★★★★';$('#mathProgress').style.width='100%';$('#mathIcon').textContent='🏆';$('#mathModeLabel').textContent='AVENTURA COMPLETA';$('#mathQuestion').textContent='És um campeão da matemática!';$('#mathSpeakBtn').classList.add('hidden');$('#equation').textContent='8 estrelas conquistadas';$('#mathTip').textContent='Muito bem! Podes repetir ou experimentar outra aventura.';$('#answers').innerHTML='<button id="repeatMath">Repetir</button><button id="swapMath">Trocar</button>';$('#repeatMath').onclick=()=>startMath(mathOperation);$('#swapMath').onclick=showMathChoice;celebrate(true);speak('Parabéns! Completaste a aventura de matemática')}
const paintCategories=[{name:'Dinossauros',icon:'🦕',row:0,drawings:['Brontossauro','Tricerátops','Estegossauro']},{name:'Carros',icon:'🚗',row:1,drawings:['Carro feliz','Carro de corrida','Jipe']},{name:'Camiões',icon:'🚚',row:2,drawings:['Camião basculante','Carro de bombeiros','Betoneira']},{name:'Motas',icon:'🏍️',row:3,drawings:['Scooter','Moto de cross','Moto clássica']},{name:'Animais',icon:'🦁',row:4,drawings:['Leão','Elefante','Girafa']}];
function showPaintChoice(){paintCategory=null;$('#paintChoice').classList.remove('hidden');$('#paintPlay').classList.add('hidden');$('#drawingPrompt').classList.add('hidden');$('#drawingChoices').innerHTML='';const box=$('#paintCategories');box.innerHTML='';paintCategories.forEach((cat,i)=>{const b=document.createElement('button');b.className='paint-category';b.innerHTML=`<span>${cat.icon}</span><strong>${cat.name}</strong><small>3 desenhos</small>`;b.onclick=()=>choosePaintCategory(i);box.appendChild(b)})}
function choosePaintCategory(index){paintCategory=index;$$('.paint-category').forEach((b,i)=>b.classList.toggle('active',i===index));$('#drawingPrompt').classList.remove('hidden');const box=$('#drawingChoices');box.innerHTML='';paintCategories[index].drawings.forEach((name,col)=>{const b=document.createElement('button');b.className='drawing-thumb';b.innerHTML=`<span></span><strong>${name}</strong>`;const preview=b.querySelector('span');preview.style.backgroundImage="url('assets/paint-atlas.png')";preview.style.backgroundSize='300% 500%';preview.style.backgroundPosition=`${col*50}% ${index*25}%`;b.onclick=()=>startPainting(index,col);box.appendChild(b)})}
function buildPalette(){const p=$('#palette');p.innerHTML='';colors.concat(['#9b5de5','#00bbf9','#8dd35f','#8b5e3c','#fff']).forEach(c=>{const b=document.createElement('button');b.style.background=c;b.onclick=()=>{paintColor=c;$$('#palette button').forEach(x=>x.classList.remove('active'));b.classList.add('active');tone(420,.05)};p.appendChild(b)});p.firstChild.classList.add('active')}
function startPainting(row,col){paintCategory=row;paintDrawing=col;$('#paintChoice').classList.add('hidden');$('#paintPlay').classList.remove('hidden');$('#paintName').textContent=paintCategories[row].drawings[col];buildPalette();drawPaintImage()}
function drawPaintImage(){if(!paintImage){paintImage=new Image();paintImage.src='assets/paint-atlas.png';paintImage.onload=drawPaintImage;return}if(!paintImage.complete)return;const c=$('#colorCanvas'),ctx=c.getContext('2d',{willReadFrequently:true}),sw=paintImage.naturalWidth/3,sh=paintImage.naturalHeight/5;ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(paintImage,paintDrawing*sw,paintCategory*sh,sw,sh,0,0,c.width,c.height)}
function hexRgb(hex){const n=parseInt(hex.slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255]}
function floodPaint(x,y,color){const c=$('#colorCanvas'),ctx=c.getContext('2d',{willReadFrequently:true}),img=ctx.getImageData(0,0,c.width,c.height),d=img.data,w=c.width,h=c.height,start=(y*w+x)*4,target=[d[start],d[start+1],d[start+2]];if((target[0]+target[1]+target[2])/3<165)return;const fill=hexRgb(color);if(Math.abs(target[0]-fill[0])+Math.abs(target[1]-fill[1])+Math.abs(target[2]-fill[2])<20)return;const stack=[y*w+x],seen=new Uint8Array(w*h);while(stack.length){const p=stack.pop();if(seen[p])continue;seen[p]=1;const i=p*4,r=d[i],g=d[i+1],b=d[i+2];if(Math.abs(r-target[0])+Math.abs(g-target[1])+Math.abs(b-target[2])>75)continue;d[i]=fill[0];d[i+1]=fill[1];d[i+2]=fill[2];const px=p%w,py=(p/w)|0;if(px>0)stack.push(p-1);if(px<w-1)stack.push(p+1);if(py>0)stack.push(p-w);if(py<h-1)stack.push(p+w)}ctx.putImageData(img,0,0);tone(520,.06)}
function canvasPaint(e){const c=$('#colorCanvas'),r=c.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)*c.width/r.width),y=Math.floor((e.clientY-r.top)*c.height/r.height);floodPaint(x,y,paintColor)}
function surprisePaint(){const palette=colors.concat(['#9b5de5','#00bbf9','#8dd35f']);for(let i=0;i<18;i++)floodPaint(30+Math.floor(Math.random()*340),30+Math.floor(Math.random()*340),palette[i%palette.length]);celebrate()}
function updateMessage(text,type=''){const box=$('#updateStatus');box.textContent=text;box.className=`update-status ${type}`;clearTimeout(updateMessage.timer);updateMessage.timer=setTimeout(()=>box.classList.add('hidden'),4200)}
let swRegistration,reloading=false,updateFound=false,manualUpdate=false;
async function checkUpdate(){if(!swRegistration){updateMessage('As atualizações automáticas não estão disponíveis','bad');return}manualUpdate=true;updateFound=false;updateMessage('🔎 A procurar uma nova versão…');$('#updateBtn').classList.add('checking');try{await swRegistration.update();setTimeout(()=>{if(!updateFound)updateMessage('✅ Já tens a versão mais recente · v1.10','good');$('#updateBtn').classList.remove('checking')},1400)}catch(e){updateMessage('Não foi possível verificar. Tenta novamente com internet.','bad');$('#updateBtn').classList.remove('checking')}}
async function setupUpdates(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(manualUpdate&&!reloading){reloading=true;location.reload()}});try{swRegistration=await navigator.serviceWorker.register('./sw.js');swRegistration.addEventListener('updatefound',()=>{updateFound=true;const worker=swRegistration.installing;updateMessage('🦕 Nova versão encontrada. A atualizar…');worker?.addEventListener('statechange',()=>{if(worker.state==='activated')updateMessage('✅ Atualização concluída!','good')})})}catch(e){updateMessage('Atualização automática indisponível','bad')}}
$$('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));$$('.operation-card').forEach(b=>b.onclick=()=>startMath(b.dataset.op));$('#speakBtn').onclick=()=>speak(currentSpeech);$('#mathSpeakBtn').onclick=()=>speak(mathSpeech);$('#changeOperation').onclick=showMathChoice;$('#nextBtn').onclick=()=>{level++;buildPairs();show('pairsScreen')};$('#backBtn').onclick=()=>{if('speechSynthesis'in window)speechSynthesis.cancel();saveBest();show('menuScreen')};$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊':'🔇';if(!sound&&'speechSynthesis'in window)speechSynthesis.cancel()};$('#updateBtn').onclick=checkUpdate;$('#updateStatus').onclick=checkUpdate;$('#paintBack').onclick=showPaintChoice;$('#colorCanvas').onclick=canvasPaint;$('#clearPaint').onclick=drawPaintImage;$('#randomPaint').onclick=surprisePaint;show('menuScreen');window.addEventListener('load',setupUpdates);
